// Invoice.jsx

import { useState, useEffect } from "react"
import { supabase } from "../supabase"
import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

export default function Invoice({ user }) {
  const [customerName, setCustomerName] = useState("")
  const [customerPhone, setCustomerPhone] = useState("")
  const [items, setItems] = useState([{ description: "", quantity: 1, price: "" }])
  const [invoiceType, setInvoiceType] = useState("receipt")
  const [generating, setGenerating] = useState(false)
  const [customers, setCustomers] = useState([])

  useEffect(() => {
    supabase.from("customers").select("name,phone").eq("user_id", user.id).then(({ data }) => {
      if (data) setCustomers(data)
    })
  }, [])

  const bizName = user?.user_metadata?.name || "My Business"
  const total = items.reduce((s, i) => s + (parseFloat(i.price) || 0) * (parseFloat(i.quantity) || 0), 0)

  function addItem() { setItems([...items, { description: "", quantity: 1, price: "" }]) }
  function updateItem(i, field, val) {
    const updated = [...items]
    updated[i][field] = val
    setItems(updated)
  }
  function removeItem(i) { setItems(items.filter((_, idx) => idx !== i)) }

  function generatePDF() {
    setGenerating(true)
    const doc = new jsPDF()
    const invoiceNum = `BB-${Date.now().toString().slice(-6)}`
    const today = new Date().toLocaleDateString("en-GH")

    // Header
    doc.setFillColor(13, 148, 136)
    doc.rect(0, 0, 210, 40, "F")
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(24)
    doc.setFont("helvetica", "bold")
    doc.text(bizName, 14, 16)
    doc.setFontSize(10)
    doc.setFont("helvetica", "normal")
    doc.text(`${invoiceType === "receipt" ? "RECEIPT" : "INVOICE"} #${invoiceNum}`, 14, 26)
    doc.text(`Date: ${today}`, 14, 33)
    doc.text("Powered by BizBuddy", 150, 20)

    // Customer
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(11)
    doc.setFont("helvetica", "bold")
    doc.text(`${invoiceType === "receipt" ? "Received from" : "Bill to"}:`, 14, 52)
    doc.setFont("helvetica", "normal")
    doc.text(customerName || "Customer", 14, 60)
    if (customerPhone) doc.text(customerPhone, 14, 67)

    // Items table
    autoTable(doc, {
      startY: 75,
      head: [["Item", "Qty", "Unit Price", "Total"]],
      body: items.filter(i => i.description).map(i => [
        i.description,
        i.quantity,
        `GHS ${parseFloat(i.price || 0).toFixed(2)}`,
        `GHS ${((parseFloat(i.price) || 0) * (parseFloat(i.quantity) || 0)).toFixed(2)}`
      ]),
      headStyles: { fillColor: [13, 148, 136], textColor: 255 },
      columnStyles: { 2: { halign: "right" }, 3: { halign: "right" } },
      styles: { fontSize: 10 }
    })

    const finalY = doc.lastAutoTable.finalY + 10
    doc.setFontSize(13)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(13, 148, 136)
    doc.text(`TOTAL: GHS ${total.toFixed(2)}`, 140, finalY)

    doc.setFontSize(9)
    doc.setTextColor(150)
    doc.setFont("helvetica", "normal")
    doc.text("Thank you for your business! 🙏", 14, finalY + 15)
    doc.text("Generated by BizBuddy • bizbuddy-fawn.vercel.app", 14, doc.internal.pageSize.height - 8)

    doc.save(`${invoiceType}_${invoiceNum}.pdf`)
    setGenerating(false)
  }

  const inputClass = "w-full bg-gray-50 dark:bg-[#1A3A38] border border-gray-200 dark:border-[#1A3A38] text-gray-800 dark:text-white rounded-xl px-3 py-2.5 text-sm focus:outline-none"

  return (
    <div className="p-4 md:p-6">
      <h1 className="text-2xl font-bold text-primary dark:text-[#2DD4BF] mb-1">Invoice & Receipt</h1>
      <p className="text-gray-500 dark:text-gray-400 text-sm mb-4">Create professional receipts instantly</p>

      <div className="bg-white dark:bg-[#112221] rounded-2xl border border-gray-100 dark:border-[#1A3A38] p-4 mb-4">
        <div className="flex gap-2 mb-4">
          <button onClick={() => setInvoiceType("receipt")} className={`flex-1 py-2 rounded-xl text-sm font-semibold ${invoiceType === "receipt" ? "bg-primary dark:bg-[#2DD4BF] text-white dark:text-[#0B1F1E]" : "bg-gray-100 dark:bg-[#1A3A38] text-gray-500 dark:text-gray-400"}`}>Receipt</button>
          <button onClick={() => setInvoiceType("invoice")} className={`flex-1 py-2 rounded-xl text-sm font-semibold ${invoiceType === "invoice" ? "bg-primary dark:bg-[#2DD4BF] text-white dark:text-[#0B1F1E]" : "bg-gray-100 dark:bg-[#1A3A38] text-gray-500 dark:text-gray-400"}`}>Invoice</button>
        </div>

        <p className="text-xs text-gray-500 dark:text-gray-400 mb-1">Customer</p>
        <select onChange={e => { const c = customers.find(c => c.name === e.target.value); if(c) { setCustomerName(c.name); setCustomerPhone(c.phone || "") }}} className={`${inputClass} mb-2`}>
          <option value="">Select from customer book...</option>
          {customers.map(c => <option key={c.name} value={c.name}>{c.name}</option>)}
        </select>
        <input placeholder="Or type customer name" value={customerName} onChange={e => setCustomerName(e.target.value)} className={`${inputClass} mb-2`} />
        <input placeholder="Phone (optional)" value={customerPhone} onChange={e => setCustomerPhone(e.target.value)} className={`${inputClass} mb-4`} />

        <p className="text-xs text-gray-500 dark:text-gray-400 mb-2 font-semibold">Items</p>
        {items.map((item, i) => (
          <div key={i} className="flex gap-2 mb-2">
            <input placeholder="Description" value={item.description} onChange={e => updateItem(i, "description", e.target.value)}
              className="flex-1 bg-gray-50 dark:bg-[#1A3A38] border border-gray-200 dark:border-[#1A3A38] text-gray-800 dark:text-white rounded-xl px-3 py-2 text-sm focus:outline-none" />
            <input type="number" placeholder="Qty" value={item.quantity} onChange={e => updateItem(i, "quantity", e.target.value)}
              className="w-14 bg-gray-50 dark:bg-[#1A3A38] border border-gray-200 dark:border-[#1A3A38] text-gray-800 dark:text-white rounded-xl px-2 py-2 text-sm focus:outline-none" />
            <input type="number" placeholder="Price" value={item.price} onChange={e => updateItem(i, "price", e.target.value)}
              className="w-20 bg-gray-50 dark:bg-[#1A3A38] border border-gray-200 dark:border-[#1A3A38] text-gray-800 dark:text-white rounded-xl px-2 py-2 text-sm focus:outline-none" />
            {items.length > 1 && <button onClick={() => removeItem(i)} className="text-red-400 text-lg">✕</button>}
          </div>
        ))}
        <button onClick={addItem} className="text-sm text-primary dark:text-[#2DD4BF] mb-4">+ Add item</button>

        <div className="bg-gray-50 dark:bg-[#1A3A38] rounded-xl p-3 mb-4 flex justify-between">
          <span className="font-semibold dark:text-white">Total</span>
          <span className="font-bold text-primary dark:text-[#2DD4BF]">GHS {total.toFixed(2)}</span>
        </div>

        <button onClick={generatePDF} disabled={generating || !customerName || total === 0}
          className="w-full bg-primary dark:bg-[#2DD4BF] text-white dark:text-[#0B1F1E] rounded-xl py-3 font-semibold disabled:opacity-50">
          {generating ? "Generating..." : `📄 Generate ${invoiceType === "receipt" ? "Receipt" : "Invoice"}`}
        </button>
      </div>
    </div>
  )
}