// Reports.jsx

import { useState, useEffect } from "react"
import { supabase } from "../supabase"
import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

export default function Reports({ user }) {
  const [transactions, setTransactions] = useState([])
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth())
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear())
  const [generating, setGenerating] = useState(false)

  const months = ["January","February","March","April","May","June","July","August","September","October","November","December"]

  useEffect(() => { loadTransactions() }, [])

  async function loadTransactions() {
    const { data } = await supabase.from("transactions").select("*")
      .eq("user_id", user.id).order("created_at", { ascending: false })
    if (data) setTransactions(data)
  }

  const filtered = transactions.filter(t => {
    const d = new Date(t.created_at)
    return d.getMonth() === selectedMonth && d.getFullYear() === selectedYear
  })

  const income = filtered.filter(t => t.type === "income").reduce((s, t) => s + Number(t.amount), 0)
  const expenses = filtered.filter(t => t.type === "expense").reduce((s, t) => s + Number(t.amount), 0)
  const net = income - expenses

  function generatePDF() {
    setGenerating(true)
    const doc = new jsPDF()
    const name = user?.user_metadata?.name || "Business Owner"
    const bizType = user?.user_metadata?.bizType || "Small Business"

    // Header
    doc.setFillColor(13, 148, 136)
    doc.rect(0, 0, 210, 35, "F")
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(22)
    doc.setFont("helvetica", "bold")
    doc.text("BizBuddy", 14, 15)
    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    doc.text(`Monthly Business Report — ${months[selectedMonth]} ${selectedYear}`, 14, 25)
    doc.text(`${name} • ${bizType}`, 14, 32)

    // Summary cards
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(11)
    doc.setFont("helvetica", "bold")
    doc.text("Financial Summary", 14, 48)

    doc.setFillColor(240, 253, 250)
    doc.roundedRect(14, 52, 56, 24, 3, 3, "F")
    doc.setTextColor(13, 148, 136)
    doc.setFontSize(9)
    doc.text("TOTAL INCOME", 18, 60)
    doc.setFontSize(13)
    doc.setFont("helvetica", "bold")
    doc.text(`GHS ${income.toLocaleString("en-GH", {minimumFractionDigits: 2})}`, 18, 70)

    doc.setFillColor(255, 241, 242)
    doc.roundedRect(76, 52, 56, 24, 3, 3, "F")
    doc.setTextColor(239, 68, 68)
    doc.setFontSize(9)
    doc.setFont("helvetica", "normal")
    doc.text("TOTAL EXPENSES", 80, 60)
    doc.setFontSize(13)
    doc.setFont("helvetica", "bold")
    doc.text(`GHS ${expenses.toLocaleString("en-GH", {minimumFractionDigits: 2})}`, 80, 70)

    doc.setFillColor(net >= 0 ? 240 : 255, net >= 0 ? 253 : 241, net >= 0 ? 250 : 242)
    doc.roundedRect(138, 52, 56, 24, 3, 3, "F")
    doc.setTextColor(net >= 0 ? 13 : 239, net >= 0 ? 148 : 68, net >= 0 ? 136 : 68)
    doc.setFontSize(9)
    doc.setFont("helvetica", "normal")
    doc.text("NET PROFIT", 142, 60)
    doc.setFontSize(13)
    doc.setFont("helvetica", "bold")
    doc.text(`GHS ${net.toLocaleString("en-GH", {minimumFractionDigits: 2})}`, 142, 70)

    // Transactions table
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(11)
    doc.setFont("helvetica", "bold")
    doc.text("Transaction Details", 14, 88)

    autoTable(doc, {
      startY: 92,
      head: [["Date", "Description", "Category", "Type", "Amount (GHS)"]],
      body: filtered.map(t => [
        new Date(t.created_at).toLocaleDateString("en-GH"),
        t.description,
        t.category || "-",
        t.type === "income" ? "Income" : "Expense",
        `${t.type === "income" ? "+" : "-"}${Number(t.amount).toLocaleString("en-GH", {minimumFractionDigits: 2})}`
      ]),
      headStyles: { fillColor: [13, 148, 136], textColor: 255, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [245, 255, 253] },
      columnStyles: { 4: { halign: "right" } },
      styles: { fontSize: 9 }
    })

    // Footer
    const pageCount = doc.internal.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(150)
      doc.text(`Generated by BizBuddy • bizbuddy-fawn.vercel.app • Page ${i} of ${pageCount}`, 14, doc.internal.pageSize.height - 8)
    }

    doc.save(`BizBuddy_Report_${months[selectedMonth]}_${selectedYear}.pdf`)
    setGenerating(false)
  }

  return (
    <div className="p-4 md:p-6">
      <h1 className="text-2xl font-bold text-primary dark:text-[#2DD4BF] mb-1">Reports</h1>
      <p className="text-gray-500 dark:text-gray-400 text-sm mb-6">Download your monthly business report</p>

      {/* Month selector */}
      <div className="bg-white dark:bg-[#112221] rounded-2xl border border-gray-100 dark:border-[#1A3A38] p-4 mb-4">
        <p className="text-sm font-semibold text-gray-700 dark:text-white mb-3">Select Period</p>
        <div className="flex gap-3">
          <select
            value={selectedMonth}
            onChange={e => setSelectedMonth(Number(e.target.value))}
            className="flex-1 bg-gray-50 dark:bg-[#1A3A38] border border-gray-200 dark:border-[#1A3A38] text-gray-800 dark:text-white rounded-xl px-3 py-2.5 text-sm focus:outline-none"
          >
            {months.map((m, i) => <option key={i} value={i}>{m}</option>)}
          </select>
          <select
            value={selectedYear}
            onChange={e => setSelectedYear(Number(e.target.value))}
            className="w-28 bg-gray-50 dark:bg-[#1A3A38] border border-gray-200 dark:border-[#1A3A38] text-gray-800 dark:text-white rounded-xl px-3 py-2.5 text-sm focus:outline-none"
          >
            {[2024, 2025, 2026].map(y => <option key={y} value={y}>{y}</option>)}
          </select>
        </div>
      </div>

      {/* Summary */}
      <div className="bg-white dark:bg-[#112221] rounded-2xl border border-gray-100 dark:border-[#1A3A38] p-4 mb-4">
        <p className="text-sm font-semibold text-gray-700 dark:text-white mb-3">
          {months[selectedMonth]} {selectedYear} Summary
        </p>
        <div className="grid grid-cols-3 gap-3 mb-4">
          <div className="text-center">
            <p className="text-xs text-gray-400 mb-1">Income</p>
            <p className="font-bold text-primary dark:text-[#2DD4BF] text-sm">GHS {income.toLocaleString()}</p>
          </div>
          <div className="text-center">
            <p className="text-xs text-gray-400 mb-1">Expenses</p>
            <p className="font-bold text-red-400 text-sm">GHS {expenses.toLocaleString()}</p>
          </div>
          <div className="text-center">
            <p className="text-xs text-gray-400 mb-1">Net</p>
            <p className={`font-bold text-sm ${net >= 0 ? "text-primary dark:text-[#2DD4BF]" : "text-red-400"}`}>GHS {net.toLocaleString()}</p>
          </div>
        </div>

        {filtered.length === 0 ? (
          <div className="text-center py-4">
            <p className="text-gray-400 text-sm">No transactions for this period</p>
          </div>
        ) : (
          <div className="max-h-48 overflow-y-auto space-y-2">
            {filtered.map(t => (
              <div key={t.id} className="flex justify-between items-center py-1.5 border-b border-gray-100 dark:border-[#1A3A38] last:border-0">
                <div>
                  <p className="text-xs font-medium dark:text-white">{t.description}</p>
                  <p className="text-xs text-gray-400">{t.category}</p>
                </div>
                <p className={`text-xs font-bold ${t.type === "income" ? "text-primary dark:text-[#2DD4BF]" : "text-red-400"}`}>
                  {t.type === "income" ? "+" : "-"}GHS {Number(t.amount).toLocaleString()}
                </p>
              </div>
            ))}
          </div>
        )}
      </div>

      <button
        onClick={generatePDF}
        disabled={generating || filtered.length === 0}
        className="w-full bg-primary dark:bg-[#2DD4BF] text-white dark:text-[#0B1F1E] rounded-xl py-3 font-semibold disabled:opacity-50"
      >
        {generating ? "Generating PDF..." : `📄 Download ${months[selectedMonth]} Report`}
      </button>

      {filtered.length === 0 && (
        <p className="text-center text-xs text-gray-400 mt-2">Add transactions for this month to generate a report</p>
      )}
    </div>
  )
}